[theme]
primaryColor = "#A32E2E"       # Vinho do design
backgroundColor = "#1A1A1D"   # Fundo Escuro
secondaryBackgroundColor = "#2D2D31" # Fundo dos Cards
textColor = "#FFFFFF"         # Texto Branco
font = "sans serif"